import { Car } from "../models/car.model";

export const carList: Car[] = [
  {
    id: '1',
    carName: 'YARIS 1.5G CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3805/_3/r0fm5k.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '650',
    fuel: '42',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '1',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '2',
    carName: 'WIGO 4AT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3951/_3/4sd30w.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '405',
    fuel: '33',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '2',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '3',
    carName: 'WIGO 5MT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3951/_3/4sd30w.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '345',
    fuel: '33',
    kmUse: '0',
    transmission : 'Số Sàn',
    isNew: true,
    model: '2',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '4',
    carName: 'VIOS 1.5E 5MT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3804/_1/otkrja.png?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '490',
    fuel: '42',
    kmUse: '0',
    transmission : 'Số Tay',
    isNew: true,
    model: '3',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '5',
    carName: 'VIOS 1.5G CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3803/_1/itd2wy.jpg?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '570',
    fuel: '42',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '3',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '6',
    carName: 'VIOS 1.5E CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3802/_1/h5n4ln.png?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '540',
    fuel: '42',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '3',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '7',
    carName: 'COROLLA ALTIS 2.0V SPORT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3133/_1/gg2dje.jpg?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '932',
    fuel: '55',
    kmUse: '0',
    transmission : 'bằng tay',
    isNew: true,
    model: '4',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '8',
    carName: 'COROLLA ALTIS 1.8E CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3131/_1/vgatgm.jpg?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '733',
    fuel: '55',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '4',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '9',
    carName: 'COROLLA ALTIS 1.8G CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3133/_1/gg2dje.jpg?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '791',
    fuel: '55',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '4',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '10',
    carName: 'CAMRY 2.0G',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/4676/_3/de0ts0.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '1029',
    fuel: '60',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '5',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '11',
    carName: 'CAMRY 2.5Q',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/4676/_1/qkft5q.png?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '1235',
    fuel: '60',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '5',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '12',
    carName: 'FORTUNER 2.4AT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/yptufv.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1096',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '6',  
    seats: '7',
    origin: '1',
    fuelType: '2'
  },
  {
    id: '13',
    carName: 'FORTUNER 2.8AT 4X4',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/31vxd5.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1354',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '6',  
    seats: '7',
    origin: '1',
    fuelType: '2'
  },
  {
    id: '14',
    carName: 'FORTUNER 2.4MT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/qmu1u1.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1033',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '15',
    carName: 'FORTUNER 2.7AT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/yptufv.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1150',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '16',
    carName: 'FORTUNER 2.7AT 4X4',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/31vxd5.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1244',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '17',
    carName: 'FORTUNER TRD 2.7AT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/qmu1u1.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '550',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: true,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '18',
    carName: 'YARIS 1.5G CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3805/_3/r0fm5k.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '650',
    fuel: '42',
    kmUse: '10000',
    transmission : 'Tự Động',
    isNew: false,
    model: '1',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '19',
    carName: 'WIGO 4AT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3951/_3/4sd30w.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '405',
    fuel: '33',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '2',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '20',
    carName: 'WIGO 5MT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3951/_3/4sd30w.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '345',
    fuel: '33',
    kmUse: '0',
    transmission : 'Số Sàn',
    isNew: false,
    model: '2',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '21',
    carName: 'VIOS 1.5E 5MT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3804/_1/otkrja.png?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '490',
    fuel: '42',
    kmUse: '0',
    transmission : 'Số Tay',
    isNew: false,
    model: '3',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '22',
    carName: 'VIOS 1.5G CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3803/_1/itd2wy.jpg?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '570',
    fuel: '42',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '3',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '23',
    carName: 'VIOS 1.5E CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3802/_1/h5n4ln.png?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '540',
    fuel: '42',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '3',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '24',
    carName: 'COROLLA ALTIS 2.0V SPORT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3133/_1/gg2dje.jpg?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '932',
    fuel: '55',
    kmUse: '0',
    transmission : 'bằng tay',
    isNew: false,
    model: '4',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '25',
    carName: 'COROLLA ALTIS 1.8E CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3131/_1/vgatgm.jpg?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '733',
    fuel: '55',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '4',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '26',
    carName: 'COROLLA ALTIS 1.8G CVT',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3133/_1/gg2dje.jpg?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '791',
    fuel: '55',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '4',  
    seats: '5',
    origin: '1',
    fuelType: '1'
  },
  {
    id: '27',
    carName: 'CAMRY 2.0G',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/4676/_3/de0ts0.png',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '1029',
    fuel: '60',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '5',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '28',
    carName: 'CAMRY 2.5Q',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/4676/_1/qkft5q.png?w=340&h=170&mode=crop',
    isSpecial: false,
    hrefUrl: '',
    carPrice: '1235',
    fuel: '60',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '5',  
    seats: '5',
    origin: '2',
    fuelType: '1'
  },
  {
    id: '29',
    carName: 'FORTUNER 2.4AT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/yptufv.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1096',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '6',  
    seats: '7',
    origin: '1',
    fuelType: '2'
  },
  {
    id: '30',
    carName: 'FORTUNER 2.8AT 4X4',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/31vxd5.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1354',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '6',  
    seats: '7',
    origin: '1',
    fuelType: '2'
  },
  {
    id: '31',
    carName: 'FORTUNER 2.4MT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/qmu1u1.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1033',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '32',
    carName: 'FORTUNER 2.7AT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/yptufv.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1150',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '33',
    carName: 'FORTUNER 2.7AT 4X4',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/31vxd5.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: '1244',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  },
  {
    id: '34',
    carName: 'FORTUNER TRD 2.7AT 4X2',
    carImageUrl: 'http://dongsaigon.toyota.com.vn/data/news/3740/_1/qmu1u1.png?w=340&h=170&mode=crop',
    isSpecial: true,
    hrefUrl: '',
    carPrice: 'Request',
    fuel: '80',
    kmUse: '0',
    transmission : 'Tự Động',
    isNew: false,
    model: '6',  
    seats: '7',
    origin: '2',
    fuelType: '2'
  }
]